const execute = require('./../connection');
const express = require('express');
const router = express.Router();



router.post("/productos_filtro", async(req,res)=>{
   
    const { token, sucursal, filtro } = req.body;

    let qry = `SELECT  PRODUCTOS.CODPROD, PRODUCTOS.CODPROD2, PRODUCTOS.DESPROD, PRODUCTOS.DESPROD2, PRODUCTOS.DESPROD3, PRODUCTOS.CODMARCA, MARCAS.DESMARCA, PRODUCTOS.TIPOPROD, 
    PRODUCTOS.EXISTENCIA, PRECIOS.CODMEDIDA, PRECIOS.EQUIVALE, PRECIOS.COSTO, PRECIOS.PRECIO, PRECIOS.MAYOREOA, PRECIOS.MAYOREOB, PRECIOS.MAYOREOC
FROM            PRODUCTOS LEFT OUTER JOIN
    MARCAS ON PRODUCTOS.CODMARCA = MARCAS.CODMARCA AND PRODUCTOS.EMPNIT = MARCAS.EMPNIT LEFT OUTER JOIN
    PRECIOS ON PRODUCTOS.CODPROD = PRECIOS.CODPROD AND PRODUCTOS.EMPNIT = PRECIOS.EMPNIT
WHERE        (PRODUCTOS.EMPNIT = '${sucursal}') 
AND (PRODUCTOS.HABILITADO = 'SI')
AND (PRODUCTOS.DESPROD LIKE '%${filtro}%')
OR
(PRODUCTOS.EMPNIT = '${sucursal}') 
AND (PRODUCTOS.HABILITADO = 'SI')
AND (PRODUCTOS.CODPROD = '${filtro}')`
    

    execute.QueryToken(res,qry,token);
     
});






module.exports = router;